server:
  port: 8882
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/zhe-ye?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #邮件发送配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2508127924@qq.com
    password: cldlmwkjqaljebhj
    properties.smtp.auth: true
    properties.smtp.timeout: 2500
    properties.mail.smtp.ssl.enable: true
  #Redis相关配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    expire: 60000
  jackson:
    date-format: yyyy-MM-dd
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.jnu.entity



  time-zone: Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  devtools:
    livereload:
      port: 35731
logging:
  level:
    com:
      jnu:
        dao=debug: debug

#全局逻辑删除配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#配置文件存储路径
file:
  rootPath: "D:/ZheYeProject/trunk/Project"
  sonPath: "/server/src/main/resources/static/img/"
  localPath: http://localhost:8882/file/img/

